import type {
  AffectedArea,
  FeatureSpec,
  ImplementationPlan,
  ImplementationStep,
} from "@repo/domain/schemas";
import type { FeatureRecord, ProjectRecord } from "@repo/db";

const AREA_LABEL: Record<AffectedArea, string> = {
  frontend: "Frontend",
  backend: "Backend",
  database: "Database",
  infrastructure: "Infrastructure",
  docs: "Docs",
  tests: "Tests",
};

function bullets(items: string[]): string {
  if (items.length === 0) return "_(none)_";
  return items.map((i) => `- ${i}`).join("\n");
}

function groupStepsByArea(
  steps: ImplementationStep[],
): Array<{ area: AffectedArea; steps: ImplementationStep[] }> {
  const groups = new Map<AffectedArea, ImplementationStep[]>();
  for (const step of steps) {
    const list = groups.get(step.area) ?? [];
    list.push(step);
    groups.set(step.area, list);
  }
  return Array.from(groups.entries()).map(([area, steps]) => ({ area, steps }));
}

function metaBlock(_feature: FeatureRecord, project: ProjectRecord): string {
  const modeLabel =
    project.mode === "greenfield" ? "Greenfield" : "Existing system";
  return [
    `**Project:** ${project.name}`,
    `**Mode:** ${modeLabel}`,
    `**Generated:** ${new Date().toISOString()}`,
  ].join("  \n");
}

export function renderSpecDoc(
  feature: FeatureRecord,
  project: ProjectRecord,
  spec: FeatureSpec,
): string {
  return (
    [
      `# ${spec.title}`,
      metaBlock(feature, project),
      "## Problem",
      spec.problem,
      "## Goal",
      spec.goal,
      "## In scope",
      bullets(spec.scope.in),
      "## Out of scope",
      bullets(spec.scope.out),
      "## Actors",
      bullets(spec.actors),
      "## User flows",
      bullets(spec.userFlows),
      "## UI states",
      bullets(spec.uiStates),
      "## Business rules",
      bullets(spec.businessRules),
      "## Data changes",
      bullets(spec.dataChanges),
      "## API changes",
      bullets(spec.apiChanges),
      "## Acceptance criteria",
      bullets(spec.acceptanceCriteria),
      "## Assumptions",
      bullets(spec.assumptions),
      "## Open questions",
      bullets(spec.openQuestions),
    ].join("\n\n") + "\n"
  );
}

export function renderPlanDoc(
  feature: FeatureRecord,
  project: ProjectRecord,
  plan: ImplementationPlan,
): string {
  const grouped = groupStepsByArea(plan.steps);

  const stepsBlock = grouped
    .map(
      ({ area, steps }) =>
        `### ${AREA_LABEL[area]}\n\n` +
        steps
          .map((s, i) => `${i + 1}. **${s.title}** — ${s.description}`)
          .join("\n"),
    )
    .join("\n\n");

  const fileChanges =
    plan.fileChanges.length === 0
      ? "_(none)_"
      : plan.fileChanges
          .map((fc) => `- \`[${fc.action}]\` \`${fc.path}\` — ${fc.summary}`)
          .join("\n");

  const risks = plan.risks
    .map((r) => `- **${r.description}**\n  Mitigation: ${r.mitigation}`)
    .join("\n");

  return (
    [
      `# Implementation plan: ${feature.title}`,
      metaBlock(feature, project),
      "## Summary",
      plan.summary,
      "## Affected areas",
      plan.affectedAreas.map((a) => `- ${AREA_LABEL[a]}`).join("\n"),
      "## File changes",
      fileChanges,
      "## Steps",
      stepsBlock,
      "## Test plan",
      bullets(plan.testPlan),
      "## Risks & edge cases",
      risks,
    ].join("\n\n") + "\n"
  );
}

import type { ConsistencyIssue } from "@repo/ai";

export interface PrBodyExtras {
  scaffoldedCount: number;
  generatedCount: number;
  modifiedCount: number;
  unverifiedFiles: string[];
  consistencyIssues: ConsistencyIssue[];
}

export function renderPrBody(
  feature: FeatureRecord,
  plan: ImplementationPlan,
  paths: { specFile: string; planFile: string },
  extras: PrBodyExtras,
): string {
  const stepsChecklist = plan.steps
    .map((s) => `- [ ] **${s.title}** — ${s.description}`)
    .join("\n");

  const risks = plan.risks
    .map((r) => `- **${r.description}** — *Mitigation:* ${r.mitigation}`)
    .join("\n");

  let fileNote = "";
  if (extras.generatedCount > 0) {
    const newCount = extras.generatedCount - extras.modifiedCount;
    const breakdown =
      extras.modifiedCount > 0 && newCount > 0
        ? ` (${newCount} new, ${extras.modifiedCount} modified)`
        : extras.modifiedCount > 0
          ? ` (all modifications)`
          : "";
    fileNote = `\n\n🤖 ${extras.generatedCount} file${extras.generatedCount === 1 ? "" : "s"}${breakdown} were generated by AI from the plan, your repo's conventions, and retrieved code context. **Review carefully — code quality varies.**`;
    if (extras.unverifiedFiles.length > 0) {
      fileNote += `\n\n⚠️ ${extras.unverifiedFiles.length} file${extras.unverifiedFiles.length === 1 ? "" : "s"} did not pass syntax verification:\n${extras.unverifiedFiles.map((p) => `- \`${p}\``).join("\n")}`;
    }
  } else if (extras.scaffoldedCount > 0) {
    fileNote = `\n\n${extras.scaffoldedCount} stub file${extras.scaffoldedCount === 1 ? "" : "s"} were scaffolded for new paths in the plan. Each contains a TODO header — fill them in step by step.`;
  }

  const consistencyBlock =
    extras.consistencyIssues.length > 0
      ? [
          `## 🔎 Cross-file consistency review`,
          `The AI flagged these potential cross-file issues — worth a closer look during review:`,
          extras.consistencyIssues
            .map((i) => `- \`${i.path}\` — ${i.description}`)
            .join("\n"),
        ].join("\n\n")
      : "";

  const sections = [
    `# ${feature.title}`,
    `${plan.summary}${fileNote}`,
    `## 📄 Generated artifacts`,
    `- [Feature spec](${paths.specFile})\n- [Implementation plan](${paths.planFile})`,
    `## ✅ Implementation steps`,
    stepsChecklist,
    `## ⚠️ Risks & edge cases`,
    risks,
  ];
  if (consistencyBlock) sections.push(consistencyBlock);
  sections.push(`---\n*Generated by ai-app-builder.*`);

  return sections.join("\n\n") + "\n";
}
